### ISSUE TITLE
Error in testperiodic

### ISSUE THREAD

**Issue by justusc** [m-a-d-n-e-s-s/madness#154]
@wsttiger 

An error introduced in 76d5489c8ae196906a94d359baefed7f5ddaa432 is causing failures in the Travis-CI tests.

The error output is:
```
	/usr/bin/mpicxx.mpich2 -DHAVE_CONFIG_H   -I../../../src -I../../../src -I../../../src/apps -DDISABLE_SSE3 -DMPICH_SKIP_MPICXX=1 -DOMPI_SKIP_MPICXX=1  -std=c++11 -mno-avx -g -Wall -Wno-strict-aliasing -Wno-deprecated -Wno-unused-local-typedefs -MT testperiodic.o -MD -MP -MF $depbase.Tpo -c -o testperiodic.o testperiodic.cc &&\
	mv -f $depbase.Tpo $depbase.Po
In file included from testperiodic.cc:18:0:
../../../src/apps/chem/xcfunctional.h:62:5: warning: multi-line comment [-Wcomment]
testperiodic.cc: In member function ‘virtual double_complex AtomicBasisFunctor::operator()(const coord_3d&) const’:
testperiodic.cc:111:30: error: ‘const class madness::AtomicBasisFunction’ has no member named ‘rangesq’
testperiodic.cc:115:38: error: ‘const class madness::AtomicBasisFunction’ has no member named ‘rangesq’
testperiodic.cc:119:46: error: ‘const class madness::AtomicBasisFunction’ has no member named ‘rangesq’
```

**Comment by wsttiger** [comment]
Should be good now ... just committed changes.
